import json

country_mapping = {
    "Italia": "Italy",
    "Austria": "Austria",
    "España": "Spain",
    "Francia": "France",
    "Alemania": "Germany",
    "Sudáfrica": "South Africa",
    "Eslovenia": "Slovenia",
    "Australia": "Australia",
    "Portugal": "Portugal",
    "Argentina": "Argentina",
    "Hungría": "Hungary",
    "Grecia": "Greece",
    "New Zealand": "New Zealand",
    "Estados Unidos": "United States",
    "Chile": "Chile",
    "Croacia": "Croatia",
    "Rumanía": "Romania",
    "Bulgaria": "Bulgaria",
    "Marruecos": "Morocco",
    "Perú": "Peru",
    "Brasil": "Brazil",
    "Líbano": "Lebanon",
    "Luxembourg": "Luxembourg",
    "Suiza": "Switzerland",
    "Japón": "Japan",
    "Georgia": "Georgia",
    "Armenia": "Armenia",
    "Ucrania": "Ukraine",
    "México": "Mexico",
    "Reino Unido": "United Kingdom",
    "Israel": "Israel",
    "República Checa": "Czech Republic",
    "Países Bajos": "Netherlands",
    "Bélgica": "Belgium",
    "Canadá": "Canada",
    "Chipre": "Cyprus",
    "Norte de Macedonia": "North Macedonia",
    "Polonia": "Poland",
    "Serbia": "Serbia",
    "Eslovaquia": "Slovakia",
    "Uruguay": "Uruguay",
    "China": "China",
    "Moldavia": "Moldova",
    "Dinamarca": "Denmark",
    "Albania": "Albania",
    "Afganistán": "Afghanistan",
    "Albania": "Albania",
    "Algeria": "Algeria",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antigua y Barbuda": "Antigua and Barbuda",
    "Arabia Saudita": "Saudi Arabia",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaiyán": "Azerbaijan",
    "Bahamas": "Bahamas",
    "Baréin": "Bahrain",
    "Bangladés": "Bangladesh",
    "Barbados": "Barbados",
    "Bélgica": "Belgium",
    "Belice": "Belize",
    "Benín": "Benin",
    "Bhután": "Bhutan",
    "Bielorrusia": "Belarus",
    "Birmania": "Myanmar",
    "Botsuana": "Botswana",
    "Brasil": "Brazil",
    "Brunéi": "Brunei",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Bután": "Bhutan",
    "Cabo Verde": "Cape Verde",
    "Camboya": "Cambodia",
    "Camerún": "Cameroon",
    "Canadá": "Canada",
    "Catar": "Qatar",
    "Chad": "Chad",
    "Chile": "Chile",
    "China": "China",
    "Chipre": "Cyprus",
    "Colombia": "Colombia",
    "Comoras": "Comoros",
    "Congo": "Congo",
    "Corea del Norte": "North Korea",
    "Corea del Sur": "South Korea",
    "Costa Rica": "Costa Rica",
    "Croacia": "Croatia",
    "Cuba": "Cuba",
    "Curazao": "Curaçao",
    "Chipre": "Cyprus",
    "República Checa": "Czech Republic",
    "Côte d'Ivoire": "Ivory Coast",
    "Dinamarca": "Denmark",
    "Djibouti": "Djibouti",
    "Dominica": "Dominica",
    "República Dominicana": "Dominican Republic",
    "Ecuador": "Ecuador",
    "Egipto": "Egypt",
    "El Salvador": "El Salvador",
    "Emiratos Árabes Unidos": "United Arab Emirates",
    "Ecuador": "Ecuador",
    "Eslovaquia": "Slovakia",
    "Eslovenia": "Slovenia",
    "España": "Spain",
    "Estados Unidos": "United States",
    "Etiopía": "Ethiopia",
    "Fiyi": "Fiji",
    "Filipinas": "Philippines",
    "Finlandia": "Finland",
    "Francia": "France",
    "Gabon": "Gabon",
    "Gambia": "Gambia",
    "Georgia": "Georgia",
    "Ghana": "Ghana",
    "Granada": "Grenada",
    "Grecia": "Greece",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guinea-Bisáu": "Guinea-Bissau",
    "Guyana": "Guyana",
    "Haití": "Haiti",
    "Honduras": "Honduras",
    "Hungría": "Hungary",
    "India": "India",
    "Indonesia": "Indonesia",
    "Irak": "Iraq",
    "Irlanda": "Ireland",
    "Isla de Man": "Isle of Man",
    "Islas Cook": "Cook Islands",
    "Islas Feroe": "Faroe Islands",
    "Islas Malvinas": "Falkland Islands",
    "Islandia": "Iceland",
    "Israel": "Israel",
    "Italia": "Italy",
    "Jamaica": "Jamaica",
    "Japón": "Japan",
    "Jordania": "Jordan",
    "Kazajistán": "Kazakhstan",
    "Kenia": "Kenya",
    "Kirguistán": "Kyrgyzstan",
    "Kiribati": "Kiribati",
    "Kuwait": "Kuwait",
    "Laos": "Laos",
    "Lesoto": "Lesotho",
    "Letonia": "Latvia",
    "Líbano": "Lebanon",
    "Liberia": "Liberia",
    "Libia": "Libya",
    "Liechtenstein": "Liechtenstein",
    "Lituania": "Lithuania",
    "Luxemburgo": "Luxembourg",
    "Madagascar": "Madagascar",
    "Malasia": "Malaysia",
    "Malaui": "Malawi",
    "Maldivas": "Maldives",
    "Malta": "Malta",
    "Marruecos": "Morocco",
    "Mauricio": "Mauritius",
    "Mauritania": "Mauritania",
    "México": "Mexico",
    "Micronesia": "Micronesia",
    "Mónaco": "Monaco",
    "Mongolia": "Mongolia",
    "Mozambique": "Mozambique",
    "Namibia": "Namibia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Nicaragua": "Nicaragua",
    "Níger": "Niger",
    "Nigeria": "Nigeria",
    "Noruega": "Norway",
    "Nueva Zelanda": "New Zealand",
    "Omán": "Oman",
    "Países Bajos": "Netherlands",
    "Pakistán": "Pakistan",
    "Palau": "Palau",
    "Panamá": "Panama",
    "Papúa Nueva Guinea": "Papua New Guinea",
    "Paraguay": "Paraguay",
    "Perú": "Peru",
    "Polonia": "Poland",
    "Portugal": "Portugal",
    "Reino Unido": "United Kingdom",
    "República Checa": "Czech Republic",
    "Rumanía": "Romania",
    "Rusia": "Russia",
    "Ruanda": "Rwanda",
    "Sahara Occidental": "Western Sahara",
    "Samoa": "Samoa",
    "San Cristóbal y Nieves": "Saint Kitts and Nevis",
    "San Marino": "San Marino",
    "Santa Lucía": "Saint Lucia",
    "Senegal": "Senegal",
    "Serbia": "Serbia",
    "Seychelles": "Seychelles",
    "Sierra Leona": "Sierra Leone",
    "Singapur": "Singapore",
    "Siria": "Syria",
    "Somalia": "Somalia",
    "Sri Lanka": "Sri Lanka",
    "Suazilandia": "Eswatini",
    "Sudán": "Sudan",
    "Sudáfrica": "South Africa",
    "Suecia": "Sweden",
    "Suiza": "Switzerland",
    "Surinam": "Suriname",
    "Siria": "Syria",
    "Somalia": "Somalia",
    "Sri Lanka": "Sri Lanka",
    "Tailandia": "Thailand",
    "Tanzania": "Tanzania",
    "Togo": "Togo",
    "Trinidad y Tobago": "Trinidad and Tobago",
    "Túnez": "Tunisia",
    "Turkmenistán": "Turkmenistan",
    "Turquía": "Turkey",
    "Tuvalu": "Tuvalu",
    "Uganda": "Uganda",
    "Ucrania": "Ukraine",
    "Uruguay": "Uruguay",
    "Uzbekistán": "Uzbekistan",
    "Vanuatu": "Vanuatu",
    "Vaticano": "Vatican",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "Yemen": "Yemen",
    "Zambia": "Zambia",
    "Zimbabue": "Zimbabwe"
}